# Generated by Django 3.2.6 on 2021-08-09 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(db_index=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woreda_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=255)),
                ('begin_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('geography_1', models.FloatField(db_index=True, max_length=255)),
                ('longitude', models.CharField(db_index=True, max_length=255)),
                ('geography_2', models.FloatField(db_index=True, max_length=255)),
                ('latitude', models.CharField(db_index=True, max_length=255)),
                ('elevation', models.FloatField(db_index=True, max_length=255)),
                ('note', models.TextField(db_index=True, max_length=500)),
                ('basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.basin')),
                ('msc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.msc')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.region')),
                ('station_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.stationtype')),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.woreda')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.zone')),
            ],
        ),
    ]
